package annotations.io;

/**
 * Like a {@link ParseException} but contains a filename. Generated by
 * <code>parse</code> methods that take a filename instead of a
 * {@link java.io.Reader}. Message looks like:
 * 
 * <pre>
 *        erroneousfile.jann:20: Expected `@'
 * </pre>
 */
public final class FileParseException extends Exception {
    private static final long serialVersionUID = 1152202248L;

    /**
     * The underlying {@link ParseException}, from which one can obtain
     * the line number and message.
     */
    public final /*@NonNull*/ ParseException pe;

    /**
     * The name of the file that was being parsed.
     */
    public final /*@NonNull*/ String filename;

    FileParseException(/*@NonNull*/ ParseException pe, /*@NonNull*/
    String filename) {
        super(filename + ":" + pe.getMessage(), pe);
        this.pe = pe;
        this.filename = filename;
    }
}
