#!/bin/sh

# Insert annotations (from an annoation file) into a class file.
# For usage information, run: insert-annotations --help 
# See the annotation file utilities documentation for more information.

ANNOTATION_FILE_UTILS=$(dirname $0)/annotation-file-utilities.jar

java -cp ${ANNOTATION_FILE_UTILS} annotations.io.classfile.ClassFileWriter $@
