#!/bin/sh

# Insert annotations (from an annotation file) into a Java source file.
# For usage information, run: insert-annotations-to-source --help 
# See the annotation file utilities documentation for more information.

ANNOTATION_FILE_UTILS=$(dirname $0)/../annotation-file-utilities.jar
# Contains Java 7 version of java.lang.annotation.ElementType.
JAVAC_JAR=${JAVAC_JAR:-$(dirname $0)/../../../jsr308-langtools/dist/lib/javac.jar}

# Augment, don't replace, CLASSPATH, so as to find user files.
# Can we can do without annotation-file-utilities.jar on bootclasspath?
java -ea -Xbootclasspath/p:${JAVAC_JAR} -classpath ${ANNOTATION_FILE_UTILS}:${CLASSPATH} annotator.Main "$@"
