#!/bin/sh

# Concatenates multiple descriptions of annotations into a single one.

SCENE_LIB=$(dirname $0)
WORKSPACE=$SCENE_LIB/..
ASMX=$WORKSPACE/asmx

TOOLS_JAR=${TOOLS_JAR:-${JAVA_HOME}/lib/tools.jar}

export CLASSPATH=${TOOLS_JAR}:$SCENE_LIB/bin:$ASMX/bin:$WORKSPACE/annotation-file-utilities/lib/plume-core.jar:$CLASSPATH
java scenelib.annotations.tools.Anncat "$@"
