#!/bin/sh

# Concatenates multiple descriptions of annotations into a single one.

SCENE_LIB=$(dirname $0)
WORKSPACE=$SCENE_LIB/..
ASMX=$WORKSPACE/asmx

JAVAC_JAR=${JAVAC_JAR:-$WORKSPACE/annotation-file-utilities/lib/javac-9-dev-r4023-3.jar}

export CLASSPATH=${JAVAC_JAR}:$SCENE_LIB/bin:$ASMX/bin:$WORKSPACE/annotation-file-utilities/lib/bcel-util-1.1.4.jar:$WORKSPACE/annotation-file-utilities/lib/options-1.0.1.jar:$WORKSPACE/annotation-file-utilities/lib/plume-util-1.0.7.jar:$WORKSPACE/annotation-file-utilities/lib/signature-util-0.0.6.jar:$CLASSPATH
java scenelib.annotations.tools.Anncat "$@"
